# Generated by Django 3.2 on 2021-04-25 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Kategori İsmi')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=55, unique=True, verbose_name='Ürün İsmi')),
                ('quantity', models.PositiveIntegerField(verbose_name='Ürün Miktarı')),
                ('content', models.TextField(blank=True, max_length=255, null=True, verbose_name='Ürün Açıklaması')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('giriş', 'Giriş'), ('çıkış', 'Çıkış')], max_length=10, verbose_name='Stok Hareketi')),
                ('action_quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='İşlem Miktarı')),
                ('action_date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih-Saat')),
                ('customer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Müşteri')),
                ('category', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='actions', to='products.product', verbose_name='Ürün İsmi')),
                ('quantity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action', to='products.product', verbose_name='Miktar')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-action_date'],
            },
        ),
    ]
